FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

# Lock npm to a stable version and install deps.
RUN corepack enable \
  && corepack prepare npm@9.8.1 --activate \
  && npm install

COPY . ./

RUN npx prisma generate

EXPOSE 8080

CMD ["npm", "run", "dev"]